### PR TITLE
Add `jq` to `mvnix-update`

### PR DESCRIPTION
**Pull request by FRidh**
Missing dependency.

### CODE REVIEW

**Comment by icetan** [comment]
I think that the `jq` bin should be included in the `yq` package. Do you get some sort of error without `jq` explicitly as a dependency?

**Comment by FRidh** [comment]
Yes, without `jq` added I get an error that it cannot be found.

That change can be made in Nixpkgs, however, it will take time before it will propagate.

**Comment by icetan** [comment]
Aha, it's weird, when I run `nix-shell --pure -p yq` I can use `jq`.

Anyway great find, thanks for the PR!

**Comment by FRidh** [comment]
Actually, I am surprised as well considering `jq` is correctly added to the `yq` wrapper...

**Pull request merged**
