### PR TITLE
Refactor for addition to Nixpkgs.

### PR DESCRIPTION
**Pull request by invokesus**
pkgs is now resolved in `default.nix` and inherited in `mavenix.nix`.

### CODE REVIEW

**Review by evanjs — APPROVED** [review]
Thanks for the PR!
Hopefully this is available in tree before too long.

Confirmed that this installs and runs `mvnix-init` and `mvnix-update` (barring #41) fine.

**Comment by evanjs** [comment]
Should we update the url in the readme as well?
```` diff
diff --git a/README.md b/README.md
index e7f979a..1ea446e 100644
--- a/README.md
+++ b/README.md
@@ -8,7 +8,7 @@ First you need to install the [Nix package manager](https://nixos.org/nix/), if
 you already haven't.

 ```sh
-nix-env -i -f https://github.com/icetan/mavenix/tarball/master
+nix-env -i -f https://github.com/nix-community/mavenix/tarball/master
 ```
````

**Comment by invokesus** [comment]
Thanks for the review! I updated the URL in the README. I'll create a PR in nixpkgs once this is merged.

**Comment by icetan** [comment]
Great work, thank you @invokesus

**Pull request merged**
